### ISSUE TITLE
PCGen 6.09.00 does not start: "Graphics Device initialization failed for : es2, sw"

### ISSUE THREAD

**Issue by allardhoeve** [PCGen/pcgen#5986]
I tried PCGen 6.09.00 on my Macbook today and it wouldn't start. PCGen 6.08.00 (final) starts perfectly as it always did.

I am on Java 11.01 (Oracle) but have also tried OpenJDK 12: same error.

I have no idea how to fix this. It seems (after searching) like a JFX error, but it looks like JFX needs to be linked into the Java application, so there is likely nothing I can do?

I know nothing about Java, so I'm at a loss how to use my favorite character editor :(

Thanks

```
$ ./pcgen.sh 
# java --version ouput manually added to pcgen.sh
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode, sharing)

Available memory: 3323128 kB
There is more than 1 GB of free memory available. Will raise memory limits.
Will take a quarter as low limit and half as upper limit:
min: 811 MB, max: 1622 MB
2019-08-16T20:19:57.022602 INFO main Main:133 Starting PCGen v6.09.00
2019-08-16T20:19:57.060298 INFO main LanguageBundle:134 Initialising language bundle with locale en_NL.
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:243)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:241)
	at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:257)
	at pcgen.system.Main.startupWithGUI(Main.java:227)
	at pcgen.system.Main.main(Main.java:152)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:835)
2019-08-16T20:19:59.995324 SEVERE main Main:474 Uncaught error on thread  Thread[main,5,main] - ignoring
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:241)
	at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:257)
	at pcgen.system.Main.startupWithGUI(Main.java:227)
	at pcgen.system.Main.main(Main.java:152)
```

**Comment by Murdoche** [comment]
Hi, so what macOS is on your macbook and have you just run the .jar file instead?

**Comment by LegacyKing** [comment]
Fixed for the next build... Coming out shortly.
