### ISSUE TITLE
Starfinder Operative Adding Levels at Character Creation

### ISSUE THREAD

**Issue by cdm014** [PCGen/pcgen#5989]
tried to create an android operative and the window stopped working until I went to another tab. when i went back it was slow to redraw. Error log:

16:17:41.73 INFO AWT-EventQueue-0 CharacterFacadeImpl:808 ibm: Adding level 1 in class Operative
16:17:41.115 SEVERE AWT-EventQueue-0 Main:484 Uncaught error - ignoring
java.lang.IllegalStateException: Cannot ask for contained objects: Reference has not been resolved
	at pcgen.cdom.reference.CDOMTypeRef.getContainedObjects(CDOMTypeRef.java:216)
	at pcgen.core.PlayerCharacter.processAbilityList(PlayerCharacter.java:8085)
	at pcgen.core.PlayerCharacter.processAbilityListsOnAdd(PlayerCharacter.java:8074)
	at pcgen.core.PlayerCharacter.processAddition(PlayerCharacter.java:9026)
	at pcgen.cdom.facet.ObjectAdditionFacet.dataAdded(ObjectAdditionFacet.java:59)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.CDOMObjectConsolidationFacet.add(CDOMObjectConsolidationFacet.java:70)
	at pcgen.cdom.facet.CDOMObjectConsolidationFacet.dataAdded(CDOMObjectConsolidationFacet.java:135)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.CharacterConsolidationFacet.dataAdded(CharacterConsolidationFacet.java:64)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractListFacet.add(AbstractListFacet.java:71)
	at pcgen.cdom.facet.model.SimpleAbilityFacet.dataAdded(SimpleAbilityFacet.java:34)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractCNASEnforcingFacet.add(AbstractCNASEnforcingFacet.java:64)
	at pcgen.cdom.facet.base.AbstractCNASEnforcingFacet.dataAdded(AbstractCNASEnforcingFacet.java:176)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractCNASEnforcingFacet.add(AbstractCNASEnforcingFacet.java:64)
	at pcgen.core.PlayerCharacter.applyAbility(PlayerCharacter.java:8143)
	at pcgen.core.PlayerCharacter.processAbilityList(PlayerCharacter.java:8126)
	at pcgen.core.PlayerCharacter.processAbilityListsOnAdd(PlayerCharacter.java:8074)
	at pcgen.core.PlayerCharacter.processAddition(PlayerCharacter.java:9026)
	at pcgen.cdom.facet.ObjectAdditionFacet.dataAdded(ObjectAdditionFacet.java:59)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.CDOMObjectConsolidationFacet.add(CDOMObjectConsolidationFacet.java:70)
	at pcgen.cdom.facet.CDOMObjectConsolidationFacet.dataAdded(CDOMObjectConsolidationFacet.java:135)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.CharacterConsolidationFacet.dataAdded(CharacterConsolidationFacet.java:64)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.model.TemplateFacet.dataAdded(TemplateFacet.java:56)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractListFacet.add(AbstractListFacet.java:71)
	at pcgen.cdom.facet.input.TemplateInputFacet.directAdd(TemplateInputFacet.java:111)
	at pcgen.cdom.facet.input.TemplateInputFacet.add(TemplateInputFacet.java:58)
	at pcgen.core.PlayerCharacter.addTemplate(PlayerCharacter.java:4592)
	at pcgen.core.PlayerCharacter.addTemplatesIfMissing(PlayerCharacter.java:8153)
	at pcgen.core.PlayerCharacter.processAddition(PlayerCharacter.java:9022)
	at pcgen.cdom.facet.ObjectAdditionFacet.dataAdded(ObjectAdditionFacet.java:59)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.CDOMObjectConsolidationFacet.add(CDOMObjectConsolidationFacet.java:70)
	at pcgen.cdom.facet.CDOMObjectConsolidationFacet.dataAdded(CDOMObjectConsolidationFacet.java:135)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.CharacterConsolidationFacet.dataAdded(CharacterConsolidationFacet.java:64)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.model.ClassFacet.addClass(ClassFacet.java:69)
	at pcgen.core.PlayerCharacter.incrementClassLevel(PlayerCharacter.java:6831)
	at pcgen.core.PlayerCharacter.incrementClassLevel(PlayerCharacter.java:6748)
	at pcgen.core.PlayerCharacter.incrementClassLevel(PlayerCharacter.java:5421)
	at pcgen.gui2.facade.CharacterFacadeImpl.addCharacterLevels(CharacterFacadeImpl.java:810)
	at pcgen.gui2.tabs.SummaryInfoTab$AddLevelsAction.actionPerformed(SummaryInfoTab.java:1366)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by theSoloBrewer** [comment]
I had the same issue with a Ysoki character. I tried this with starfinder core rules and society rules, and core only. this however, does not happen when you use core supplements.

**Comment by theSoloBrewer** [comment]
I was messing around with it today, this was working in 6.07 so I started messing with the pcc files and added the armory to the society pcc and it would allow me to add a class rank without the error.

**Comment by LegacyKing** [comment]
Sounds like Code issue, and not a Data issue. Since you've got this working closing.
