### ISSUE TITLE
Pathfinder: Swashbuckler Ronin Favored Weapon Choice can't be selected

### ISSUE THREAD

**Issue by BarracudaLP97** [PCGen/pcgen#6024]
I have a Kitsune Ninja, Sorcerer and Swashbuckler and can't select a Katana as my favored weapon due to this error: 

> "Failed to add Ability due to Only EquipmentToken should call itself as a Converter"

The log shows this. I'm guessing this is the only important part looking at it. I'll also add my Character File just in case you need it. [Tomio.zip](https://github.com/PCGen/pcgen/files/3612040/Tomio.zip)

```
00:47:31.715 SEVERE AWT-EventQueue-0 CharacterAbilities:371 Failed to add ability due to 
java.lang.UnsupportedOperationException: Only EquipmentToken should call itself as a Converter
	at plugin.qualifier.weaponprof.EquipmentToken.convert(EquipmentToken.java:166)
	at plugin.primitive.equipment.WieldCategoryToken.getCollection(WieldCategoryToken.java:133)
	at pcgen.cdom.primitive.CompoundAndPrimitive.getCollection(CompoundAndPrimitive.java:94)
	at plugin.qualifier.weaponprof.EquipmentToken.getCollection(EquipmentToken.java:136)
	at pcgen.cdom.choiceset.CollectionToChoiceSet.getSet(CollectionToChoiceSet.java:62)
	at pcgen.cdom.base.BasicChooseInformation.getSet(BasicChooseInformation.java:232)
	at pcgen.core.chooser.CDOMChoiceManager.getChoices(CDOMChoiceManager.java:58)
	at pcgen.core.AbilityUtilities.processSelection(AbilityUtilities.java:243)
	at pcgen.core.AbilityUtilities.driveChooseAndAdd(AbilityUtilities.java:232)
	at pcgen.gui2.facade.CharacterAbilities.addAbility(CharacterAbilities.java:367)
	at pcgen.gui2.facade.CharacterFacadeImpl.addAbility(CharacterFacadeImpl.java:669)
	at pcgen.gui2.tabs.AbilityChooserTab$AddAction.actionPerformed(AbilityChooserTab.java:566)
	at pcgen.gui2.util.JTableEx.fireActionEvent(JTableEx.java:127)
	at pcgen.gui2.util.JTableEx$1.mouseClicked(JTableEx.java:104)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by LegacyKing** [comment]
Confirmed

**Comment by LegacyKing** [comment]
Jira Ticket opened. Closing this issue. https://pcgenorg.atlassian.net/browse/CODE-3485
